on:
    push:
        branches:
            - main

name: Pages

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: docker://pandoc/core:3.8
              with:
                args: >-
                    --from markdown+smart --to=html5 --css=static/css/styling.css -s
                    index.md
                    -o index.html
            - run: |-
                mkdir -p dist/
                mv index.html dist/
            - run: |-
                cp -r ./static ./dist/static/
            - uses: actions/upload-pages-artifact@v3
              with:
                  path: dist

    deploy:
        runs-on: ubuntu-latest
        needs: build
        permissions:
            pages: write
            id-token: write
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/deploy-pages@v4
              id: deployment
